
package com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://everson.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param getAllCustomerDetailRequest
     * @return
     *     returns com.client.GetAllCustomerDetailResponse
     */
    @WebMethod(operationName = "GetAllCustomerDetail")
    @WebResult(name = "GetAllCustomerDetailResponse", targetNamespace = "http://soap.com.br", partName = "GetAllCustomerDetailResponse")
    public GetAllCustomerDetailResponse getAllCustomerDetail(
        @WebParam(name = "GetAllCustomerDetailRequest", targetNamespace = "http://soap.com.br", partName = "GetAllCustomerDetailRequest")
        GetAllCustomerDetailRequest getAllCustomerDetailRequest);

    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns com.client.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://soap.com.br", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://soap.com.br", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

    /**
     * 
     * @param deleteCustomerDetailRequest
     * @return
     *     returns com.client.DeleteCustomerDetailResponse
     */
    @WebMethod(operationName = "DeleteCustomerDetail")
    @WebResult(name = "DeleteCustomerDetailResponse", targetNamespace = "http://soap.com.br", partName = "DeleteCustomerDetailResponse")
    public DeleteCustomerDetailResponse deleteCustomerDetail(
        @WebParam(name = "DeleteCustomerDetailRequest", targetNamespace = "http://soap.com.br", partName = "DeleteCustomerDetailRequest")
        DeleteCustomerDetailRequest deleteCustomerDetailRequest);

}
